name: tech_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  jiffy: ^5.0.0
  intl: ^0.17.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  onboarding: ^3.1.0
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.8
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  flutter_local_notifications: ^14.0.0+2
  cloud_firestore: ^4.7.0
  sqflite: ^2.0.2+1
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.4
  dropdown_search: ^5.0.2
  badges: ^3.1.1
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  google_sign_in: ^6.1.0
  device_preview: ^1.1.0
  responsive_builder: ^0.6.4
  image_pickers: ^2.0.0+2
  path: ^1.8.0
  flutter_otp_text_field: ^1.0.1
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^4.0.4
  shimmer: ^2.0.0
  lottie: ^2.3.2
  cached_network_image: ^3.2.3
  awesome_select: ^6.0.0
  sticky_headers: ^0.3.0+2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
